# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: b4675f8c1426906ff25dbf5dc703facd391360da $
Configuration parameters:
  url = https://bus.miraheze.org/wiki/
  name = mihz

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'mihz'
        self.langs = {
            'zh': 'bus.miraheze.org',
        }

    def scriptpath(self, code):
        return {
            'zh': '/w',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'zh': u'1.25.3',
        }[code]

    def protocol(self, code):
        return {
            'zh': u'https',
        }[code]
